// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgoNg_BewI_LR2tITLrmMCBE_QA4M_Ss',
    appId: '1:432626101068:web:9bff0243e51ff0049f3de9',
    messagingSenderId: '432626101068',
    projectId: 'fir-chatapp-362a4',
    authDomain: 'fir-chatapp-362a4.firebaseapp.com',
    storageBucket: 'fir-chatapp-362a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRhCGOp3h9AtVeBZN8kT6XEkxzaCHqmsQ',
    appId: '1:432626101068:android:68b456f2c91dad1a9f3de9',
    messagingSenderId: '432626101068',
    projectId: 'fir-chatapp-362a4',
    storageBucket: 'fir-chatapp-362a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6_Yo-k0hmRogrL8Ifo9QTAz1qU3Yr-c',
    appId: '1:432626101068:ios:1efea94a249657069f3de9',
    messagingSenderId: '432626101068',
    projectId: 'fir-chatapp-362a4',
    storageBucket: 'fir-chatapp-362a4.appspot.com',
    iosClientId: '432626101068-k9kf5a67f7bl1c5ccio1c1qcgupnlm2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappflutter',
  );
}
